### ISSUE TITLE
 Is this repository still maintained? Issues with installing and outdated dependencies

### ISSUE THREAD

**Issue by dushmanta05** [gfazioli/VagrantUbuntu#2]
I was trying to install this config from the repo, but I ran into a lot of errors. My PHP version is 8.3, and it seems like php5-fpm is deprecated. Additionally, the repo targets Ubuntu 14.04, which is outdated and no longer supported.

The WP Bones documentation recommends this repo for setup, but it doesn't appear to work with modern environments. Are there any plans to update or maintain this? If not, could you suggest any alternatives?

I wasn’t able to understand most of the errors, so it would be incredibly helpful if this could be updated to support newer systems. Thanks so much—I really appreciate your time on this!

**Comment by gfazioli** [comment]
@dushmanta05 we updated this repo, but I didn't get any chance to try it. If you find any issues, please report them here or check this doc https://wordpress.com/blog/2022/11/14/setting-up-your-local-development-environment-for-wordpress/ where you can find a more suitable solution as well

**Comment by dushmanta05** [comment]
Thank you so much for looking into this and providing a quick update. I really appreciate your efforts! I will try it out and update you.
